### ISSUE TITLE
Write tests for Variant and EITDataVariant

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#120]

**Comment by DaniBodor** [comment]
How about using terminology related to "channel" rather than "variant"?

I suggest this because until now I was really struggling to wrap my head around what a variant is and how they should all relate to each other. Coming from an imaging background, I tried to relate it to how this would be done in an image, and realized that there, each of these would (or at least could) be a separate channel in the image. I think the usage of "variants" is very analogous to channels of an image, so maybe it would be useful to adhere to that terminology/nomenclature to make this clear.

I now realize that it goes even further in that all of our "continuous data" and "sparse data" are also just more channels of the same object, although it is a bit funky in that they (can) have different frequencies. Not really sure what the practical implication of this is last point is, just a realization I had and figured I'd share it as well.

**Comment by psomhorst** [comment]
Dropped due to removal of Variants
